### ISSUE TITLE
Battery feature not working

### ISSUE THREAD

**Issue by S-Pardo** [Gerschtli/dwm-status#10]
Enabling battery feature in config file makes program crash with the following message:
`15:50:14 [ERROR] Error in battery: no ac name (AC or ACAD) matched in /sys/class/power_supply`
```
$ ls /sys/class/power_supply
ADP1  BAT0
```

upower is installed and the daemon enabled and running through `systemctl`

**Comment by Gerschtli** [comment]
Thank you for reporting this issue, actually I'm currently working on rewriting the battery feature because of other known bugs.

If you are interested in a quick fix, could you provide some further information: Is there a file called `online` in `ADP1` which changes content if you plug in your charger?
Or do you have multiple batteries?

Could you run
```
grep . /sys/class/power_supply/*/*
```

**Comment by S-Pardo** [comment]
I have only one battery, and yes, the `online` file exists and changes when the charger is plugged in.

Looking inside the code I found that in the `ac_adapters.rs` file is the declaration for the error I was getting, which is the result of not passing the 2 ifs check on `AcAdapter::ac_exists()`.

I tried changing the AC1 constant to `const AC1: &str = "BAT0";` since BAT0 is the directory that contains all the information about the battery, but doing so resulted in:
`[ERROR] Error in battery: error reading BAT0/online (Os { code: 2, kind: NotFound, message: "No such file or directory" })`

Since you mentioned the `online` file in ADP1, tried changing the constant to ADP1 and now it works!
checked the information and it's correct.

I know you probably knew this would work, but I wrote the entire procedure in case someone else encounters the same problem.
I'm glad you made this software and will continue using and recommending it :+1: :100:

**Comment by Gerschtli** [comment]
Oh thank you for your kind words!

That was indeed the fix I would have recommended.

I hope to get this more robust soon :)

**Comment by Gerschtli** [comment]
Maybe if you like, you may checkout my `fix-battery` branch. Will release it next week after testing it thoroughly :)

**Comment by Gerschtli** [comment]
The fix is available in the latest release :)
