### ISSUE TITLE
how to start?

### ISSUE THREAD

**Issue by x4m3** [Gerschtli/dwm-status#2]
hi,
i tried to run dwm-status with one of the example files `dwm-status examples/default-settings/defaults.toml`, and i get this error:

```
23:10:21 [WARN] Config option 'debug' is deprecated and will be removed in 2.0.0. Log level is set to info by default.
23:10:21 [ERROR] Error in settings: no features enabled
```

how to enable features? and shouldn't the example be working? am i missing something?

thanks

**Comment by Gerschtli** [comment]
hey, you need to set `order` as documented in the readme under general options. in `examples/default-settings` you can see only the default settings.

**Comment by x4m3** [comment]
ohh right! my bad, i actually did `order = [audio, time]` and that didnt work... maybe i should learn toml lol.

either way, thanks!

i might start using dwm full time with dwm-status, maybe expect some patches from me :)

**Comment by Gerschtli** [comment]
I'm looking forward to your input! dwm is great tool, maybe you want to have a look at my dwm patches for some inspiration (https://github.com/Gerschtli/dwm) ;)
