### ISSUE TITLE
Battery capacity rounding error

### ISSUE THREAD

**Issue by almielczarek** [Gerschtli/dwm-status#3]
.On my machine sometimes the capacity for my battery is buggy and shows a really low percentage such as the following:

Charge Now: 45260000
Charge Full: 59920000
Capacity (as calculated in BatteryDevice.capacity()): 3
The real capacity should be about 75

I obtained these numbers by inserting a println! in the capacity method of the battery device implementation. I think this happens because the code is trying to do the multiplication and division with integers. I could be wrong, but I think floats may be needed here.

In my own copy of the repo I was able to make this work by doing the capacity calculation using floats and converting back to a u32 in the return statement.

I can send a PR if you think the change makes sense.

**Comment by Gerschtli** [comment]
The problem seems to be that charge_now multipied with 100 exceeds the u32 limit. I think converting the values to u64 should solve the issue.

I would appreciate a PR!

Thanks a lot for opening this ticket, I'm glad to see my app gets used! :)

**Comment by Gerschtli** [comment]
Issue is fixed in 1.6.1!
