### ISSUE TITLE
The battery feature report "NO BATT"

### ISSUE THREAD

**Issue by loustak** [Gerschtli/dwm-status#6]
In my config file I enabled the battery feature. Yet it doesn't report any battery data, it just display `NO BATT` as defined in the config file in case of no battery found.

When `dwm-status` is running I get the following error because of the battery feature:
`Error in dbus: failed to send message (D-Bus error: The name org.freedesktop.UPower was not provided by any .service files (org.freedesktop.DBus.Error.ServiceUnknown))`

On my system the `acpi` command returns the following:
```
Battery 0: Charging, 18%, 00:36:43 until charged
Battery 1: Unknown, 4%
```

I'm running arch linux on a lenovo thinkpad T400.

**Comment by Gerschtli** [comment]
Do you have the upower daemon installed and running?

**Comment by loustak** [comment]
Okay installing `upower` seems to solve the problem.
