### ISSUE TITLE
dwm-status stop when battery runs low

### ISSUE THREAD

**Issue by loustak** [Gerschtli/dwm-status#8]
When my battery become low (around 21%) dwm-status stop to update the bar and more, seems to just completly crash. No message is printed in the log file. When tihs happen I simply restart the program using the following command: `dwm-status ~/config/dwm-status/examples/default-settings/defaults.json &`. Here is my config file:
```
{
  "debug": false,
  "order": ["network", "audio", "backlight", "battery", "time"],
  "separator": " / ",
  "audio": {
    "control": "Master",
    "mute": "ﱝ MUTE",
    "template": "{ICO} {VOL}%",
    "icons": ["奄", "奔", "墳"]
  },
  "backlight": {
    "device": "intel_backlight",
    "template": "{ICO} {BL}%",
    "icons": ["", "", ""]
  },
  "battery": {
    "charging": "",
    "discharging": "",
    "enable_notifier": true,
    "no_battery": "",
    "notifier_critical": 10,
    "notifier_levels": [
      2,
      5,
      10,
      15,
      20
    ],
    "separator": " · ",
    "icons": ["", "", "", "", "", "", "", "", "", "", ""]
  },
  "cpu_load": {
    "template": "{CL1} {CL5} {CL15}",
    "update_interval": 20
  },
  "network": {
    "no_value": "NA",
    "template": " {ESSID}"
  },
  "time": {
    "format": "%Y-%m-%d %H:%M",
    "update_seconds": false
  }
}
```

I'm using archlinux + dwm. I think that maybe some powersaving feature kill dwm-status to preserve battery but it's pure supposition.

Any ideas how to fix the issue?

**Comment by Gerschtli** [comment]
Thats a tough one.. Are you sure you aren't getting any output of dwm-status? Could you try setting the env variable `RUST_BACKTRACE=1` and try to reproduce the error?

What kind of powersaving do you use?

Could you test to enable the features separately? Maybe this error is caused by one specific feature or occurs with any config.

This all could help me to get closer to the real problem. Thank you for your report! :)

**Comment by loustak** [comment]
Ok, I found a way to work around the problem, I set the `enable_notifier` property of the battery feature to false in the config file and this seems to solve the problem.

How notifications works? Because on my system (arh + dwm) it seems to broke dwm-status.

**Comment by Gerschtli** [comment]
Internally it uses libnotify. Do you have libnotify installed or a libnotfiy-client like dunst installed?

The library I use to interact with libnotify is https://github.com/hasufell/rust-libnotify. Maybe this lib needs a fix.. 

The only file I'm using the library is here: https://github.com/Gerschtli/dwm-status/blob/master/src/wrapper/libnotify.rs. Maybe you have an idea, what the error might solve.

**Comment by loustak** [comment]
No I don't have libnotify-client installed. Maybe this was crashing because it was trying to use a non-existing lib...

**Comment by Gerschtli** [comment]
Could you try it with an installed client? If this would solve the problem, I could clarify the instructions in the readme.
