### ISSUE TITLE
Arch Linux AUR package

### ISSUE THREAD

**Issue by yiyangc91** [Gerschtli/dwm-status#9]
Hi!

Ran into this project and it was exactly what I was looking for in a status bar (without having to write my own). Really awesome stuff.

Any chance of getting a PKGBUILD up and posted onto the AUR for Arch Linux?

**Comment by Gerschtli** [comment]
I don't run Arch and have never written a PKGBUILD before. But I would look forward to merge a PR or provide the necessary input to write a PKGBUILD.

How does it work to add a package to AUR?

**Comment by yiyangc91** [comment]
Hi Gerschtli,

A PKGBUILD is sort of just a descriptor (written in sh) for how to build the project. It contains things like:

- The package name, version, description, source
- A list of files or upstream git repo
- functions for pre build, post build, pre install and post install.
- Dependencies required for install
- Dependencies required for build

A utility supplied by arch will create a package which can then be uploaded to the Arch User Repository https://aur.archlinux.org/

It usually doesn't make a whole lot of sense to store the PKGBUILD in the same repository because conflates repo source with distribution (opinions may vary). Instead a separate git repo is used and the package repo can be hosted on the AUR (as well as github as a separate remote)

```
$ git init
$ git add PKGBUILD etc etc
$ git remote add aur ssh://aur@aur.archlinux.org/pkgbase.git
$ git push aur
```

E.g. this is an example repository containing the PKGBUILD for st. https://aur.archlinux.org/cgit/aur.git/tree/?h=st.

Happy to submit a PKGBUILD or to provide an example.

**Comment by Gerschtli** [comment]
How about you providing a working PKGBUILD and I will integrate updating it on each release?

For the needed dependencies have a look at the README.md (or default.nix if you are familiar with nix).

**Comment by Gerschtli** [comment]
And it would be good, if there were any automatic checks in travis or similar to check if the PKGBUILD is correct, because I have no possibility to verify.

**Comment by Gerschtli** [comment]
If someone wants to write a PKGBUILD, I would appreciate it, but as this issue is inactive since november I close the issue.
